{"name": "test_login_with_invalid_email_and_valid_password_Duplicate", "status": "passed", "start": 1695711019568, "stop": 1695711021900, "uuid": "59844344-9b2d-4797-acfd-f08b75cafd03", "historyId": "97eea31a395f9e802bec8794824b1cfb", "testCaseId": "97eea31a395f9e802bec8794824b1cfb", "fullName": "Tests.test_Login(duplicate).TestPanarayLoginDuplicate#test_login_with_invalid_email_and_valid_password_Duplicate", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Login(duplicate)"}, {"name": "subSuite", "value": "TestPanarayLoginDuplicate"}, {"name": "host", "value": "WONIT11L32CV6Z"}, {"name": "thread", "value": "21668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Login(duplicate)"}]}